credentials:
  usernames:
    landolfom:
      name: Landolfo M
      password: $2b$12$lrKtGEWVjChIet6A8e8x6eqEt5VMs6M.pKYL1dGlJBdflLgfugnJ.
    ballie:
      name: Balli E
      password: $2b$12$.fvzkPUzteu5cDwY3sRJFOEoG/z1Cih83wG7r0aC.hM5fnVZie2Ju
    guest:
      name: Guest
      password: $2b$12$hAodaErH08BRfVQ3FoqYjeLp1tOslvJ7BkX7t4SNBt5atHeRt9XGy
    user1:
      name: User 1
      password: $2b$12$Exp0fvlMBXYDgdVyf3I7U.HjxbNsp8w657o3C7wLk0rlggoZrFgPa
    user2:
      name: User 2
      password: $2b$12$Exp0fvlMBXYDgdVyf3I7U.HjxbNsp8w657o3C7wLk0rlggoZrFgPa
    user3:
      name: User 3
      password: $2b$12$Exp0fvlMBXYDgdVyf3I7U.HjxbNsp8w657o3C7wLk0rlggoZrFgPa
    user4:
      name: User 4
      password: $2b$12$Exp0fvlMBXYDgdVyf3I7U.HjxbNsp8w657o3C7wLk0rlggoZrFgPa
    user5:
      name: User 5
      password: $2b$12$Exp0fvlMBXYDgdVyf3I7U.HjxbNsp8w657o3C7wLk0rlggoZrFgPa
    user6:
      name: User 6
      password: $2b$12$Exp0fvlMBXYDgdVyf3I7U.HjxbNsp8w657o3C7wLk0rlggoZrFgPa
    user7:
      name: User 7
      password: $2b$12$Exp0fvlMBXYDgdVyf3I7U.HjxbNsp8w657o3C7wLk0rlggoZrFgPa
    user8:
      name: User 8
      password: $2b$12$Exp0fvlMBXYDgdVyf3I7U.HjxbNsp8w657o3C7wLk0rlggoZrFgPa
    user9:
      name: User 9
      password: $2b$12$Exp0fvlMBXYDgdVyf3I7U.HjxbNsp8w657o3C7wLk0rlggoZrFgPa
    user10:
      name: User 10
      password: $2b$12$Exp0fvlMBXYDgdVyf3I7U.HjxbNsp8w657o3C7wLk0rlggoZrFgPa
cookie:
  expiry_days: 0  # number of days until password is asked again
  key: NA5Q4IC1aqMN2vDeDH3pFjiRPr7FYMGq # Must be string, use https://randomkeygen.com/
  name: streamlitcookie
